-------------------------------------------------
-- @AUTHOR: JORANDEBOEVER
-- @SINCE: 9/12/17
-------------------------------------------------
TRUNCATE TABLE spr_selected_choice;

ALTER TABLE SPR_SELECTED_CHOICE
  DROP CONSTRAINT FK02_SPR_SELECTED_CHOICE;
DROP INDEX FK02_SPR_SELECTED_CHOICE RESTRICT;

ALTER TABLE SPR_SELECTED_CHOICE
  DROP COLUMN FOOD_OPTION_UUID;

ALTER TABLE SPR_SELECTED_CHOICE
  ADD COLUMN SIZE_UUID VARCHAR(36);