CREATE TABLE SPR_PERSON (
  UUID     VARCHAR(36)  CONSTRAINT NN00_SPR_PERSON NOT NULL,
  USERNAME VARCHAR(256) CONSTRAINT NN01_SPR_PERSON NOT NULL,
  PASSWORD VARCHAR(256),
  ENABLED  INTEGER
);

ALTER TABLE SPR_PERSON
  ADD CONSTRAINT PK_SPR_PERSON PRIMARY KEY (UUID);


CREATE TABLE AUTHORITIES (
  UUID        VARCHAR(36)  CONSTRAINT NN00_AUTHORITIES NOT NULL,
  PERSON_UUID VARCHAR(256) CONSTRAINT NN01_AUTHORITIES NOT NULL,
  AUTHORITY   VARCHAR(256)
);

ALTER TABLE AUTHORITIES
  ADD CONSTRAINT PK_AUTHORITIES PRIMARY KEY (UUID);

CREATE INDEX fk01_AUTHORITIES
  ON AUTHORITIES (PERSON_UUID);
ALTER TABLE AUTHORITIES
  ADD CONSTRAINT fk01_AUTHORITIES FOREIGN KEY (PERSON_UUID) REFERENCES SPR_PERSON (UUID);

