
CREATE TABLE SPR_PERSON (
  UUID     VARCHAR2(36 CHAR) CONSTRAINT NN00_SPR_PERSON NOT NULL,
  USERNAME VARCHAR(256 CHAR) CONSTRAINT NN01_SPR_PERSON NOT NULL,
  PASSWORD VARCHAR(256 CHAR),
  ENABLED  INTEGER
);

ALTER TABLE SPR_PERSON
  ADD CONSTRAINT PK_SPR_PERSON PRIMARY KEY (UUID);


CREATE TABLE AUTHORITIES (
  UUID      VARCHAR2(36 CHAR) CONSTRAINT NN00_AUTHORITIES NOT NULL,
  PERSON_UUID  VARCHAR(256 CHAR) CONSTRAINT NN01_AUTHORITIES NOT NULL,
  AUTHORITY VARCHAR(256)
);

ALTER TABLE AUTHORITIES
  ADD CONSTRAINT PK_AUTHORITIES PRIMARY KEY (UUID);

create index fk01_AUTHORITIES on AUTHORITIES(PERSON_UUID);
alter table AUTHORITIES add constraint fk01_AUTHORITIES foreign key (PERSON_UUID) references SPR_PERSON(UUID);

