-------------------------------------------------
-- @AUTHOR: JORANDEBOEVER
-- @SINCE: 8/12/17
-------------------------------------------------
ALTER TABLE SPR_FOOD_OPTION_CONFIG ADD CONSTRAINT UN01_SPR_FOOD_OPTION_CONFIG UNIQUE(NAME, EVENT_UUID);

ALTER TABLE SPR_FOOD_OPTION ADD CONSTRAINT UN01_SPR_FOOD_OPTION UNIQUE(NAME, CONFIGURATION_UUID);
