-------------------------------------------------
-- @AUTHOR: JORANDEBOEVER
-- @SINCE: 2/12/17
-------------------------------------------------

CREATE TABLE SPR_EXTRA_OPTION (
  UUID             VARCHAR(36) CONSTRAINT NN00_SPR_EXTRA_OPTION NOT NULL,
  NAME             VARCHAR(36) CONSTRAINT NN01_SPR_EXTRA_OPTION NOT NULL,
  PRICE            INTEGER,
  FOOD_OPTION_UUID VARCHAR(36) CONSTRAINT NN02_SPR_EXTRA_OPTION NOT NULL
);

ALTER TABLE SPR_EXTRA_OPTION
  ADD CONSTRAINT PK_SPR_EXTRA_OPTION PRIMARY KEY (UUID);

CREATE INDEX FK01_SPR_EXTRA_OPTION
  ON SPR_EXTRA_OPTION (FOOD_OPTION_UUID);
ALTER TABLE SPR_EXTRA_OPTION
  ADD CONSTRAINT FK01_SPR_EXTRA_OPTION FOREIGN KEY (FOOD_OPTION_UUID) REFERENCES SPR_FOOD_OPTION (UUID);
