-------------------------------------------------
-- @AUTHOR: JORANDEBOEVER
-- @SINCE: 3/12/17
-------------------------------------------------
CREATE TABLE SPR_SELECTED_EXTRA (
  SELECTED_CHOICE_UUID VARCHAR(36) CONSTRAINT NN00_SPR_SELECTED_EXTRA NOT NULL,
  EXTRA_OPTION_UUID    VARCHAR(36) CONSTRAINT NN01_SPR_SELECTED_EXTRA NOT NULL
);

ALTER TABLE SPR_SELECTED_EXTRA
  ADD CONSTRAINT PK_SPR_SELECTED_EXTRA PRIMARY KEY (SELECTED_CHOICE_UUID, EXTRA_OPTION_UUID);

