CREATE TABLE SPR_EVENT (
  UUID     VARCHAR2(40 CHAR) CONSTRAINT NN00_SPR_EVENT NOT NULL ,
  NAME     VARCHAR2(255 CHAR),
  DATETIME TIMESTAMP CONSTRAINT NN01_SPR_EVENT NOT NULL,
  OWNER_UUID     VARCHAR2(40 CHAR) CONSTRAINT NN02_SPR_EVENT NOT NULL,
  CONFIGURATION_UUID     VARCHAR2(40 CHAR) CONSTRAINT NN03_SPR_EVENT NOT NULL
);

ALTER TABLE SPR_EVENT
  ADD CONSTRAINT PK_SPR_EVENT PRIMARY KEY (UUID);

CREATE INDEX FK01_SPR_EVENT ON SPR_EVENT(OWNER_UUID);
ALTER TABLE SPR_EVENT ADD CONSTRAINT FK01_SPR_EVENT FOREIGN KEY (OWNER_UUID) REFERENCES SPR_PERSON(UUID);

CREATE INDEX FK02_SPR_EVENT ON SPR_EVENT(CONFIGURATION_UUID);
ALTER TABLE SPR_EVENT ADD CONSTRAINT FK02_SPR_EVENT FOREIGN KEY (CONFIGURATION_UUID) REFERENCES SPR_FOOD_OPTION_CONFIG(UUID);

ALTER TABLE SPR_EVENT ADD CONSTRAINT UN01_SPR_EVENT UNIQUE(NAME);