CREATE TABLE SPR_EVENT (
  UUID               VARCHAR(40) CONSTRAINT NN00_SPR_EVENT NOT NULL,
  NAME               VARCHAR(255),
  DATETIME           TIMESTAMP   CONSTRAINT NN01_SPR_EVENT NOT NULL,
  OWNER_UUID         VARCHAR(40) CONSTRAINT NN02_SPR_EVENT NOT NULL
);

ALTER TABLE SPR_EVENT
  ADD CONSTRAINT PK_SPR_EVENT PRIMARY KEY (UUID);

CREATE INDEX FK01_SPR_EVENT
  ON SPR_EVENT (OWNER_UUID);
ALTER TABLE SPR_EVENT
  ADD CONSTRAINT FK01_SPR_EVENT FOREIGN KEY (OWNER_UUID) REFERENCES SPR_PERSON (UUID);

ALTER TABLE SPR_EVENT
  ADD CONSTRAINT UN01_SPR_EVENT UNIQUE (NAME);