CREATE TABLE SPR_FOOD_OPTION_CONFIG (
  UUID       VARCHAR2(36 CHAR) CONSTRAINT NN00_FOOD_OPTION_CONFIG NOT NULL,
  OWNER_UUID VARCHAR2(36 CHAR)
);

ALTER TABLE SPR_FOOD_OPTION_CONFIG
  ADD CONSTRAINT PK_SPR_FOOD_OPTION_CONFIG PRIMARY KEY (UUID);

create index fk01_SPR_FOOD_OPTION_CONFIG on SPR_FOOD_OPTION_CONFIG(OWNER_UUID);
alter table SPR_FOOD_OPTION_CONFIG add constraint fk01_SPR_FOOD_OPTION_CONFIG foreign key (OWNER_UUID) references SPR_PERSON(UUID);


CREATE TABLE SPR_FOOD_OPTION (
  UUID  VARCHAR2(36 CHAR)  CONSTRAINT NN00_SPR_FOOD_OPTION NOT NULL,
  CONFIGURATION_UUID  VARCHAR2(36 CHAR)  CONSTRAINT NN01_SPR_FOOD_OPTION NOT NULL,
  NAME  VARCHAR2(255 CHAR) CONSTRAINT NN02_SPR_FOOD_OPTION NOT NULL,
  PRICE INTEGER
);

ALTER TABLE SPR_FOOD_OPTION
  ADD CONSTRAINT PK_SPR_FOOD_OPTION PRIMARY KEY (UUID);

create index fk01_SPR_FOOD_OPTION on SPR_FOOD_OPTION(CONFIGURATION_UUID);
alter table SPR_FOOD_OPTION add constraint fk01_SPR_FOOD_OPTION foreign key (CONFIGURATION_UUID) references SPR_FOOD_OPTION_CONFIG(UUID);

